name: Build CI

on:
    schedule:
        - cron: '0 0 * * *' # run at 12 AM UTC

jobs:
    build:
        name: Nightly build
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: npm install -g yarn
            - run: yarn install
            - run: yarn make
              env:
                  CI: true
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: vijayo-nightly-${{matrix.os}}
                  path: out/make/
