name: Build CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: npm install -g yarn
            - run: yarn install
            - name: Test vijayo
              uses: GabrielBB/xvfb-action@v1.0
              with:
                  run: yarn test
              env: 
                  CI: true
    build-win:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: npm install -g yarn
            - run: yarn install
            - run: yarn make
              env:
                  CI: true
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: npm install -g yarn
            - run: yarn install
            - run: yarn make
              env:
                  CI: true
    build-mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: npm install -g yarn
            - run: yarn install
            - run: yarn make
              env:
                  CI: true
