name: Test CI

on:
    - pull_request
    - push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: npm install -g yarn
            - run: yarn install
            - run: yarn package
            - name: Test vijayo
              uses: GabrielBB/xvfb-action@v1.0
              with:
                  run: yarn test
              env:
                  CI: true
